CREATE TABLE SUBJECTS(
SUBNO VARCHAR2(20),
SUBNAME VARCHAR(30)
);

INSERT INTO SUBJECTS VALUES('D20','Algorithm');
INSERT INTO SUBJECTS VALUES('D30','DataStructure');
INSERT INTO SUBJECTS VALUES('D30','C');
INSERT INTO SUBJECTS VALUES('D20','C++');
INSERT INTO SUBJECTS VALUES('D30','Python');
INSERT INTO SUBJECTS VALUES('D30','DBMS');
INSERT INTO SUBJECTS VALUES('D10','LinkedList');
INSERT INTO SUBJECTS VALUES('D20','Matrix');
INSERT INTO SUBJECTS VALUES('D10','String');
INSERT INTO SUBJECTS VALUES('D20','Tree');

SELECT * FROM SUBJECTS;
 
  
SELECT LISTAGG(SUBNAME, ' , ') WITHIN GROUP (ORDER BY SUBNAME) AS MYSUBJECTS
FROM SUBJECTS;
  
SELECT SUBNO,LISTAGG(SUBNAME, ' , ') WITHIN GROUP (ORDER BY SUBNAME) AS MYSUBJECTS
FROM SUBJECTS
GROUP BY SUBNO;


  
SELECT SUBNO,LISTAGG(SUBNAME, ',') WITHIN GROUP (ORDER BY SUBNAME) AS MYSUBJECTS
FROM SUBJECTS
GROUP BY SUBNO
ORDER BY SUBNO;
