SELECT NAME FROM VENDOR V 
INNER JOIN PRODUCT P ON(V.V_code = P.P_code)
GROUP BY NAME
HAVING COUNT(*)>1;

SELECT NAME,COUNT(*) PRODUCT_COUNT
FROM PRODUCT P,VENDER V
WHERE P.P_code=V.V_code
GROUP BY NAME
HAVING PRODUCT_COUNT > 1;


SELECT * FROM PRODUCT
WHERE SALARY > (SELECT AVG(SALARY) FROM PRODUCT);

SELECT NAME,ADDRESS,PHONE FROM VENDOR WHERE V_CODE IN
(SELECT * FROM PRODUCT WHERE P_CODE IS NULL);
